# Generated by Django 5.1.3 on 2024-12-02 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
