# Generated by Django 5.1.1 on 2024-10-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
