# Generated by Django 5.1.2 on 2024-10-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_product_imageurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='total_rating',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='imageurl',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.CharField(default='Description', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='hey', upload_to='products/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_ingredients',
            field=models.CharField(default='Ingredients', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Product', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='product_shelflife',
            field=models.CharField(default='Shelflife', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
