# Generated by Django 5.1.2 on 2024-11-19 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_productsubscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsubscription',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productsubscription',
            old_name='user_id',
            new_name='user',
        ),
    ]
