# Generated by Django 5.1.2 on 2024-11-19 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_product_id_productsubscription_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsubscription',
            old_name='isActive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='productsubscription',
            old_name='nextMonthly',
            new_name='next_monthly',
        ),
    ]
