# Generated by Django 5.1.1 on 2024-11-01 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsettings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
